# Snakemake pipeline for analyzing gwas summary statistic data using flash
#
#
# LICENSE: CC0. Do what you want with the code, but it has no guarantees.
#          https://creativecommons.org/share-your-work/public-domain/cc0/
#
#
# source activate cause_large
#
# ./run_snakemake.sh
#
# don't forget to update cluster.yaml


import pandas as pd
from snakemake.utils import validate

localrules: all, summ_to_cor
###### Load configuration file
configfile: "config.yaml"
#validate(config, schema="schemas/config.schema.yaml")

ss = pd.read_csv(config["input"]["sum_stats"], na_filter=False)

kmax = str(config["analysis"]["kmax"])
seeds = config["analysis"]["seeds"]

max_missing = config["analysis"]["max_missing"]
norm_type = config["analysis"]["norm_type"]
method = config["analysis"]["method"]
p_thresh = config["analysis"]["flash_pthresh"]

data_dir = config["out"]["data_dir"] #where the data is
out_dir = config["out"]["output_dir"] #where results will go
formatted_gwas_dir = config["out"]["formatted_gwas_dir"]
data_prefix = config["out"]["data_prefix"]
results_prefix = config["out"]["results_prefix"]

est_L = config["analysis"]["est_L"]

n_sub = config["analysis"]["n_sub"]
seeds = config["analysis"]["seeds"]

if est_L:
    inp = expand(out_dir + results_prefix + "estL_{nt}_{m}_maxmiss{maxm}_pthresh{pt}_seed{s}_sub{ns}.gwas.tsv",
                 nt = norm_type, m = method, maxm = max_missing, pt = p_thresh, s = seeds, ns = n_sub)
else:
    inp = expand(out_dir + results_prefix + "fit_{nt}_{m}_maxmiss{maxm}_pthresh{pt}_seed{s}_sub{ns}.RDS",
                 nt = norm_type, m = method, maxm = max_missing, pt = p_thresh, s = seeds, ns = n_sub)

rule all:
    input: inp



rule format:
    input: raw_data  = lambda wildcards: ss[ss['name'] == wildcards.name]['raw_data_path'].tolist()[0]
    output: out = formatted_gwas_dir + "{name}.vcf.bgz"
    params:
        snp = lambda wildcards: ss[ss['name'] == wildcards.name]['snp'].tolist()[0],
        A1 = lambda wildcards: ss[ss['name'] == wildcards.name]['A1'].tolist()[0],
        A2 = lambda wildcards: ss[ss['name'] == wildcards.name]['A2'].tolist()[0],
        beta_hat = lambda wildcards: ss[ss['name'] == wildcards.name]['beta_hat'].tolist()[0],
        se = lambda wildcards: ss[ss['name'] == wildcards.name]['se'].tolist()[0],
        chrom = lambda wildcards: ss[ss['name'] == wildcards.name]['chrom'].tolist()[0],
        pos = lambda wildcards: ss[ss['name'] == wildcards.name]['pos'].tolist()[0],
        p_value = lambda wildcards: ss[ss['name'] == wildcards.name]['p_value'].tolist()[0],
        sample_size = lambda wildcards: ss[ss['name'] == wildcards.name]['sample_size'].tolist()[0],
        is_or = lambda wildcards: ss[ss['name'] ==wildcards.name]['effect_is_or'].tolist()[0],
        neale_format = lambda wildcards: ss[ss['name'] ==wildcards.name]['neale_format'].tolist()[0],
        neale_var_ref = config["input"]["neale_var_ref"]
    shell: 'Rscript R/1_format_data_withukb.R {input.raw_data} {params.snp} {params.A1} \
            {params.A2} {params.beta_hat} {params.se} {params.chrom} {params.pos} {params.p_value} \
            {params.is_or} {params.sample_size} {output.out} {params.neale_format} {params.neale_var_ref}'

# Make a matrix that is snps by studies one for each chromosome
rule snp_table_chrom:
    input: files = expand(formatted_gwas_dir + "{name}.vcf.bgz", name = ss['name'])
    output: out =  data_dir + data_prefix + "normbeta.{norm_type}.{chrom}.RDS",
            nmiss = data_dir + data_prefix + "nmiss.{norm_type}.{chrom}.RDS"
    params: gwas_info = config["input"]["sum_stats"], d = formatted_gwas_dir
    shell: 'Rscript R/2_combine_data_vcf.R {wildcards.chrom} {params.gwas_info} {wildcards.norm_type}\
           {params.d} {output.out} {output.nmiss}'


# This one uses plink clumping. Much faster.
rule ld_prune_plink:
    input: nmiss = data_dir + data_prefix + "nmiss.{norm_type}.{chrom}.RDS",
           bfile = config["analysis"]["ref_path"] + ".bed"
    output: out = data_dir + data_prefix + "nm_ldpruned_plink.{norm_type}.{chrom}.RDS"
    params: r2_thresh = config["analysis"]["r2_plink"],
            ref_path = config["analysis"]["ref_path"]
    shell:   'Rscript R/3_ld_prune_chrom_plink.R {input.nmiss} {wildcards.chrom}  \
                   {params.r2_thresh} {params.ref_path} {output.out}'


## Estimate R
rule score_summ:
    input: normbeta =  data_dir + data_prefix + "normbeta.{norm_type}.{chrom}.RDS",
           keep = data_dir + data_prefix + "nm_ldpruned_plink.{norm_type}.{chrom}.RDS"
    output: summ =  data_dir + data_prefix + "normbeta_summary.{norm_type}.{chrom}.RDS",
            normbeta = data_dir + data_prefix + "normbeta_ldpruned_plink.{norm_type}.{chrom}.RDS"
    params: pthresh = config["analysis"]["R_pthresh"]
    shell: 'Rscript R/3_compute_summary.R {input.normbeta} {input.keep} {params.pthresh} {output.summ} {output.normbeta}'

# Compute R from the per chromosome summaries
rule summ_to_cor:
    input: expand(data_dir + data_prefix + "normbeta_summary.{{norm_type}}.{chrom}.RDS", chrom = range(1, 23))
    output: out = data_dir + data_prefix + "R_estimate.{norm_type}.RDS"
    shell: "Rscript R/4_summary_to_cor.R  {output.out} {input}"

# Run flash

rule run_flash_subsample:
    input: NB = expand(data_dir + data_prefix + "normbeta_ldpruned_plink.{{norm_type}}.{chrom}.RDS", chrom = range(1, 23)),
           R = data_dir + data_prefix + "R_estimate_ldsc.{norm_type}.RDS"
    output:  out = out_dir + results_prefix + "fit_{norm_type}_{method}_maxmiss{maxm}_pthresh{pt}_seed{s}_sub{ns}.RDS"
    params: k = kmax
    # wildcard_constraints: pthresh = "^[0-9]+[.]?[0-9]+$", min_non_miss = "\d+", norm_type = "'ss'|'z'"
    shell: 'Rscript R/5_run_flash_subsample.R {output.out} {input.R} \
            {params.k} {wildcards.method} {wildcards.norm_type} {wildcards.seed} \
            {wildcards.mxm} {wildcards.pt} {wildcards.ns} {input.NB}'


rule est_L:
    input:  fit  = out_dir + results_prefix + "fit_{norm_type}_{type}_{min_non_miss}nomiss_{pthresh}_seed{seed}_sub{ns}.RDS",
            data =  data_dir + data_prefix + "normbeta.{norm_type}.{chrom}.RDS",
            R = data_dir + data_prefix + "R_estimate.{norm_type}.RDS"
    output: out = out_dir + results_prefix + "estL_{norm_type}_{type}_{min_non_miss}nomiss_{pthresh}_seed{seed}_sub{ns}.{chrom}.RDS"
    wildcard_constraints: chrom = "\d+"
    shell: 'Rscript R/6_est_L_z.R  {input.fit} {input.data} {input.R} {output.out}'

rule write_gwas:
    input: estL = expand(out_dir + results_prefix + "estL_{{prefix}}.{chrom}.RDS", chrom=range(1, 23))
    output: out = out_dir + results_prefix + "estL_{prefix}.gwas.tsv"
    shell: 'Rscript R/8_format_estL.R  {output.out} {input.estL} '

